"""
Step 3: Transformation rules generated by Azure AI Foundry / Azure OpenAI.

Takes the assessment + DQ output, builds a prompt, calls Azure OpenAI (Foundry uses same API),
and returns structured transformation rules or code (SQL, Python/Pandas, or Dataflow-style).
Config via env: AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY, AZURE_OPENAI_DEPLOYMENT.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional

# Optional: use openai package with Azure
try:
    from openai import AzureOpenAI
    _AZURE_OPENAI_AVAILABLE = True
except ImportError:
    AzureOpenAI = None  # type: ignore
    _AZURE_OPENAI_AVAILABLE = False


def _get_azure_openai_config() -> Optional[Dict[str, str]]:
    """Read Azure OpenAI config from env (or config file if you add one)."""
    endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT") or os.environ.get("OPENAI_API_BASE")
    key = os.environ.get("AZURE_OPENAI_API_KEY") or os.environ.get("OPENAI_API_KEY")
    deployment = os.environ.get("AZURE_OPENAI_DEPLOYMENT") or os.environ.get("AZURE_OPENAI_CHAT_DEPLOYMENT")
    api_version = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-02-01")
    if not endpoint or not key or not deployment:
        return None
    return {"endpoint": endpoint.rstrip("/"), "key": key, "deployment": deployment, "api_version": api_version}


# Actions the data_transformer can apply (must match agent output)
APPLIABLE_ACTIONS = {
    "trim", "parse_dates", "fill_or_drop", "coerce_numeric", "clip_or_flag",
    "deduplicate", "deduplicate_or_alert", "standardize_type",
    "currency_normalize", "replace_values", "uppercase", "lowercase",
    "fill_forward", "fill_backward", "fill_sequence",
    "standardize_boolean", "word_to_number", "normalize_phone",
    "regex_replace", "range_clip",
}


def _build_prompt(dq_summary_text: str, language: str = "sql") -> str:
    _hints = {
        "sql": "Generate SQL (e.g. T-SQL or Spark SQL) to fix the issues.",
        "python": "Generate Python/Pandas code to fix the issues.",
        "both": "Suggest both SQL and Python/Pandas where useful.",
    }
    language_hint = _hints.get((language or "both").lower(), _hints["both"])
    actions_list = ", ".join(sorted(APPLIABLE_ACTIONS))

    return f"""You are a data quality and ETL expert. Below are data quality issues from an automated assessment.
For each issue, generate concrete transformation rules or code to fix the data.

{language_hint}
- Prefer one fix per dataset/column where possible.
- Include brief comments.
- Output code in markdown code blocks with language tag (sql or python).
- If you cannot generate code for an issue, suggest a short manual action.

IMPORTANT: You MUST also output a JSON block with structured rules we can apply automatically.
Use ONLY these actions: {actions_list}
Map issues as: whitespace→trim, nulls→fill_or_drop, invalid_date_format→parse_dates, invalid_numeric/mixed_types→coerce_numeric, currency→currency_normalize, words→word_to_number, phone→normalize_phone, negative_values→clip_or_flag, duplicate_rows→deduplicate. Optional: replace_values, uppercase, lowercase, fill_forward, fill_sequence, standardize_boolean, regex_replace, range_clip.

Output a JSON block (use ```json) with this exact structure:
{{"rules": [{{"dataset": "dataset_name", "column": "col_name", "action": "trim", "message": "brief reason"}}, ...]}}
For dataset-level actions (deduplicate), omit "column" or set it to null.

Data quality issues:
{dq_summary_text}

Respond with:
1. A short summary of the fixes (bullet list).
2. Code blocks for each transformation (use ```sql or ```python).
3. A ```json block containing the "rules" array for automatic application.
"""


def _parse_json_block(text: str) -> Optional[Dict[str, Any]]:
    """Extract and parse JSON from a ```json ... ``` block."""
    match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", text, re.DOTALL)
    if not match:
        return None
    raw = match.group(1).strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return None


def _parse_structured_rules(response_text: str) -> List[Dict[str, Any]]:
    """
    Extract structured rules from the agent response (JSON block with "rules" array).
    Filters to only appliable actions and normalizes format.
    """
    parsed = _parse_json_block(response_text)
    if not parsed or "rules" not in parsed:
        return []
    rules: List[Dict[str, Any]] = []
    for r in parsed.get("rules", []):
        dataset = r.get("dataset")
        if not dataset or dataset == "global":
            continue
        action = (r.get("action") or "").strip().lower()
        if action not in APPLIABLE_ACTIONS:
            # standardize_type maps to coerce_numeric
            if action == "standardize_type":
                action = "coerce_numeric"
            else:
                continue
        col = r.get("column")
        # For deduplicate, column can be omitted
        if action in ("deduplicate", "deduplicate_or_alert"):
            rules.append({"dataset": dataset, "column": None, "action": action, "message": r.get("message", "")})
        elif col:
            rules.append({"dataset": dataset, "column": col, "action": action, "message": r.get("message", "")})
    return rules


def _parse_agent_response(response_text: str) -> Dict[str, Any]:
    """Extract code blocks, summary, and structured rules from the model response."""
    blocks: List[Dict[str, str]] = []
    summary_lines: List[str] = []
    current_lang = ""
    current_code: List[str] = []
    in_block = False

    for line in response_text.split("\n"):
        m = re.match(r"^```(\w*)\s*$", line)
        if m:
            if in_block:
                blocks.append({"language": current_lang or "text", "code": "\n".join(current_code)})
                current_code = []
            in_block = True
            current_lang = (m.group(1) or "").lower() or "text"
            continue
        if in_block and line.strip() == "```":
            in_block = False
            if current_code:
                blocks.append({"language": current_lang or "text", "code": "\n".join(current_code)})
                current_code = []
            current_lang = ""
            continue
        if in_block:
            current_code.append(line)
        else:
            stripped = line.strip()
            if stripped and (stripped.startswith("-") or stripped.startswith("*") or stripped[0].isdigit()):
                summary_lines.append(stripped)

    if current_code and in_block:
        blocks.append({"language": current_lang or "text", "code": "\n".join(current_code)})

    structured_rules = _parse_structured_rules(response_text)

    return {
        "summary_bullets": summary_lines,
        "code_blocks": blocks,
        "structured_rules": structured_rules,
        "raw_response": response_text[:8000],
    }


def generate_transformation_rules(
    assessment_result: Dict[str, Any],
    *,
    language: str = "sql",
    dq_summary_text: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Call Azure OpenAI (Foundry) to generate transformation rules/code from the assessment.

    assessment_result: output of load_and_profile().
    language: "sql" | "python" | "both" (hint for the model).
    dq_summary_text: optional pre-built summary; if None, build_dq_summary_for_agent() is used.

    Returns:
      {
        "success": bool,
        "summary_bullets": [...],
        "code_blocks": [ {"language": "sql"|"python", "code": "..."}, ... ],
        "raw_response": str (truncated),
        "error": str | None
      }
    """
    if not _AZURE_OPENAI_AVAILABLE:
        return {
            "success": False,
            "summary_bullets": [],
            "code_blocks": [],
            "structured_rules": [],
            "raw_response": "",
            "error": "openai package not installed. pip install openai",
        }

    cfg = _get_azure_openai_config()
    if not cfg:
        return {
            "success": False,
            "summary_bullets": [],
            "code_blocks": [],
            "structured_rules": [],
            "raw_response": "",
            "error": "Azure OpenAI not configured. Set AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY, AZURE_OPENAI_DEPLOYMENT",
        }

    if dq_summary_text is None:
        from agent.transformation_suggester import build_dq_summary_for_agent
        dq_summary_text = build_dq_summary_for_agent(assessment_result)

    prompt = _build_prompt(dq_summary_text, language=language)

    try:
        client = AzureOpenAI(
            api_key=cfg["key"],
            api_version=cfg["api_version"],
            azure_endpoint=cfg["endpoint"],
        )
        response = client.chat.completions.create(
            model=cfg["deployment"],
            messages=[
                {"role": "system", "content": "You are a data engineer. Generate clear transformation code to fix data quality issues."},
                {"role": "user", "content": prompt},
            ],
            max_tokens=4000,
            temperature=0.2,
        )
        text = response.choices[0].message.content if response.choices else ""
        parsed = _parse_agent_response(text)
        return {
            "success": True,
            "summary_bullets": parsed["summary_bullets"],
            "code_blocks": parsed["code_blocks"],
            "structured_rules": parsed.get("structured_rules", []),
            "raw_response": parsed["raw_response"],
            "error": None,
        }
    except Exception as e:
        return {
            "success": False,
            "summary_bullets": [],
            "code_blocks": [],
            "structured_rules": [],
            "raw_response": "",
            "error": str(e),
        }


def generate_transformation_rules_with_suggestions(assessment_result: Dict[str, Any], language: str = "sql") -> Dict[str, Any]:
    """
    Full Step 3: rule-based suggestions + agent-generated rules/code.
    Returns both the structured suggestions and the agent output.
    """
    from agent.transformation_suggester import suggest_transformations, build_dq_summary_for_agent

    suggested = suggest_transformations(assessment_result)
    agent_result = generate_transformation_rules(
        assessment_result,
        language=language,
        dq_summary_text=build_dq_summary_for_agent(assessment_result),
    )
    return {
        "suggested_transformations": suggested,
        "agent_generated": agent_result,
    }
